version: '3'
services:
    app:
        build:
            context: ./.docker/runtimes/8.2
            dockerfile: Dockerfile
            args:
                WWWGROUP: '${WWWGROUP:-1000}'
        image: app
        container_name: app
        ports:
            - '${APP_PORT:-80}:80'
        environment:
            WWWUSER: '${WWWUSER:-1000}'
            IGNITION_LOCAL_SITES_PATH: '${PWD}'
        volumes:
            - '.:/var/www/html'
        networks:
            - pp-desafio-backend
        depends_on:
            - mysql
            - redis
            # - meilisearch
            # - mailpit
            # - selenium
    mysql:
        image: 'mysql/mysql-server:8.0'
        container_name: db
        ports:
            - '${FORWARD_DB_PORT:-3306}:3306'
        environment:
            MYSQL_ROOT_PASSWORD: '${DB_PASSWORD}'
            MYSQL_ROOT_HOST: '%'
            MYSQL_DATABASE: '${DB_DATABASE}'
            MYSQL_USER: '${DB_USERNAME}'
            MYSQL_PASSWORD: '${DB_PASSWORD}'
            MYSQL_ALLOW_EMPTY_PASSWORD: 1
        volumes:
            - 'pp-desafio-backend-mysql:/var/lib/mysql'
        networks:
            - pp-desafio-backend
        healthcheck:
            test:
                - CMD
                - mysqladmin
                - ping
                - '-p${DB_PASSWORD}'
            retries: 3
            timeout: 5s
    redis:
        image: 'redis:alpine'
        container_name: redis
        ports:
            - '${FORWARD_REDIS_PORT:-6379}:6379'
        volumes:
            - 'pp-desafio-backend-redis:/data'
        networks:
            - pp-desafio-backend
        healthcheck:
            test:
                - CMD
                - redis-cli
                - ping
            retries: 3
            timeout: 5s
    # meilisearch:
    #     image: 'getmeili/meilisearch:latest'
    #     ports:
    #         - '${FORWARD_MEILISEARCH_PORT:-7700}:7700'
    #     volumes:
    #         - 'pp-desafio-backend-meilisearch:/meili_data'
    #     networks:
    #         - pp-desafio-backend
    #     healthcheck:
    #         test:
    #             - CMD
    #             - wget
    #             - '--no-verbose'
    #             - '--spider'
    #             - 'http://localhost:7700/health'
    #         retries: 3
    #         timeout: 5s
    # mailpit:
    #     image: 'axllent/mailpit:latest'
    #     ports:
    #         - '${FORWARD_MAILPIT_PORT:-1025}:1025'
    #         - '${FORWARD_MAILPIT_DASHBOARD_PORT:-8025}:8025'
    #     networks:
    #         - pp-desafio-backend
    # selenium:
    #     image: selenium/standalone-chrome
    #     extra_hosts:
    #         - 'host.docker.internal:host-gateway'
    #     volumes:
    #         - '/dev/shm:/dev/shm'
    #     networks:
    #         - pp-desafio-backend
networks:
    pp-desafio-backend:
        driver: bridge
volumes:
    pp-desafio-backend-mysql:
        driver: local
    pp-desafio-backend-redis:
        driver: local
    # pp-desafio-backend-meilisearch:
    #     driver: local
